# Generated by Django 2.2.4 on 2019-08-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_auto_20190626_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMeteorologicalBuoy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dataset',),
        ),
    ]
